name: Deploy

on:
  push:
    branches: [ $default-branch ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Build
        run: npm run build:ci

      - name: Generate Screenshots
        run: npm run build:screenshots

      - name: Verify
        run: npm run build:verify

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
